### ISSUE TITLE
packages in by-name cannot depend on each other

### ISSUE THREAD

**Issue by katexochen** [mightyiam/by-name#6]
In the current design, a package in by-name cannot depend on another package in by name. I'd say that this would be an essential feature to make such a function useful.

**Comment by mightyiam** [comment]
Thank you, @katexochen. I would like to fix this.

**Comment by mightyiam** [comment]
Since a `callPackage` is provided by the caller, wouldn't this behavior be the responsibility of the caller?

**Comment by katexochen** [comment]
Yes, that's true.

I found https://noogle.dev/f/lib/packagesFromDirectoryRecursive#example, the example seems to do everything needed to have both, a recursive package set and a filesystem to packages by-name.
